# Hugo build configuration for Netlify
# (https://gohugo.io/hosting-and-deployment/hosting-on-netlify/#configure-hugo-version-in-netlify)

[build]
command = "./build.sh build:preview"
publish = "public"

[build.environment]
GO_VERSION = "1.22.2"

[context.production]
command = "./build.sh build:production"
